npc_scrape_omit = [
'https://wiki.project1999.com/Mobs_By_Level',
'http://web.archive.org/web/20021129210131/http://www.geocities.com/ficticiousname9/',
'https://wiki.project1999.com/index.php?title=Category:NPCs&oldid=328565',
'',
'previous 200',
'Disclaimer',
'Create new user',
'Wiki markup help',
'Install P99',
'navigation',
'search',
'Merchants',
'Named Mobs',
'Raid Encounters',
'Category',
'Discussion',
'View source',
'History',
'Create account',
'Log in',
'Main page',
'Zones',
'Quests',
'NPCs',
'Equipment',
'Armor Sets',
'Clickies',
'Resist Gear',
'Lore of Norrath',
'Languages',
'Deities',
'Factions',
'Guides',
'Game Mechanics',
'Races',
'Classes',
'Skills',
'Disciplines',
'Tradeskills',
'Cultural Tradeskills',
'Spells',
'Pet Guide',
'Haste Guide',
'Newbie Guide',
'Gear Reference',
'Player List from Live',
'Auction Price Tracker',
'Magelo (Blue)',
'Magelo (Red)',
'Magelo (Green)',
'Random Page',
'What links here',
'Related changes',
'Special pages',
'Printable version',
'Permanent link',
'Page information',
'Privacy policy',
'About Project 1999 Wiki',
'Disclaimers',
'next 200',
]
omit_these = ['None', 'Null', '', 'Error', None, "?", "???", "??", "Opposing Factions", "Related Quests"]
convert_to_none = ["()", "?", "??", "???", "????", "Various", "Multiple", "Description needed.", "Triggered"]
item_scrape_omit = ['next 200', 'previous 200']